services:
  - type: web
    name: exotel-call-processor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: EXOTEL_SID
        sync: false
      - key: EXOTEL_API_KEY
        sync: false
      - key: EXOTEL_API_TOKEN
        sync: false
      - key: SLACK_WEBHOOK
        sync: false
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_CHANNEL
        sync: false
      - key: PORT
        value: 10000